# Generated by Django 6.1.1 on 2026-09-29 07:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('memory_before_mb', models.FloatField()),
                ('memory_after_mb', models.FloatField()),
                ('memory_freed_mb', models.FloatField()),
                ('percent_before', models.FloatField(default=0.0)),
                ('percent_after', models.FloatField(default=0.0)),
                ('processes_trimmed', models.IntegerField(default=0)),
                ('initiated_by', models.CharField(default='Avinash', max_length=100)),
                ('details', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('cpu_percent', models.FloatField(help_text='Overall CPU usage %')),
                ('cpu_frequency_mhz', models.FloatField(default=0.0, help_text='Current CPU frequency in MHz')),
                ('memory_percent', models.FloatField(help_text='RAM usage %')),
                ('memory_used_gb', models.FloatField(help_text='RAM used in GB')),
                ('memory_total_gb', models.FloatField(help_text='Total RAM in GB')),
                ('memory_available_gb', models.FloatField(default=0.0, help_text='Available RAM in GB')),
                ('swap_percent', models.FloatField(default=0.0, help_text='Swap/Pagefile usage %')),
                ('disk_percent', models.FloatField(help_text='Primary disk usage %')),
                ('disk_used_gb', models.FloatField(help_text='Primary disk used GB')),
                ('disk_total_gb', models.FloatField(help_text='Primary disk total GB')),
                ('network_sent_mb', models.FloatField(default=0.0, help_text='Total MB sent')),
                ('network_recv_mb', models.FloatField(default=0.0, help_text='Total MB received')),
                ('active_processes_count', models.IntegerField(default=0)),
                ('health_score', models.IntegerField(default=100, help_text='Health Score (0-100)')),
                ('status_level', models.CharField(choices=[('OPTIMAL', 'Optimal'), ('NORMAL', 'Normal'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='OPTIMAL', max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
